// <auto-generated />
using System;
using ControleDeEstoque.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleDeEstoque.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405174703_Criandobanco")]
    partial class Criandobanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleDeEstoque.Domain.Entities.ProdutoModel", b =>
                {
                    b.Property<int>("cdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cdProduto"));

                    b.Property<double>("Preco")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("dtCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("imgProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nmProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("qtdEstoque")
                        .HasColumnType("integer");

                    b.HasKey("cdProduto");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
