// <auto-generated />
using System;
using ControleDeEstoque.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleDeEstoque.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526012214_AjusteNomesChavesEstrangeirasMovimentacao")]
    partial class AjusteNomesChavesEstrangeirasMovimentacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleDeEstoque.Domain.Entities.MotivosModel", b =>
                {
                    b.Property<int>("cdMotivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cdMotivo"));

                    b.Property<bool?>("cancelado")
                        .HasColumnType("boolean");

                    b.Property<string>("dsMotivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("dtAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("dtCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nmMotivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tpMotivo")
                        .HasColumnType("integer");

                    b.HasKey("cdMotivo");

                    b.ToTable("cadMotivos");
                });

            modelBuilder.Entity("ControleDeEstoque.Domain.Entities.MovimentacaoEstoqueModel", b =>
                {
                    b.Property<int>("cdMovimentacaoEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cdMovimentacaoEstoque"));

                    b.Property<bool?>("cancelado")
                        .HasColumnType("boolean");

                    b.Property<int>("cdMotivo")
                        .HasColumnType("integer");

                    b.Property<int>("cdProduto")
                        .HasColumnType("integer");

                    b.Property<string>("dsObservacao")
                        .HasColumnType("text");

                    b.Property<DateTime?>("dtAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dtMovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("qtMovimentacao")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("qtSaldoFinal")
                        .HasColumnType("numeric");

                    b.Property<string>("tpMovimentacao")
                        .HasColumnType("text");

                    b.Property<decimal?>("vlTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vlUnitario")
                        .HasColumnType("numeric");

                    b.HasKey("cdMovimentacaoEstoque");

                    b.HasIndex("cdMotivo");

                    b.HasIndex("cdProduto");

                    b.ToTable("cadMovimentacaoEstoque");
                });

            modelBuilder.Entity("ControleDeEstoque.Domain.Entities.ProdutoModel", b =>
                {
                    b.Property<int>("cdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cdProduto"));

                    b.Property<double>("Preco")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("dtCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("imgProduto")
                        .HasColumnType("text");

                    b.Property<string>("nmProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("qtdEstoque")
                        .HasColumnType("integer");

                    b.Property<int>("tipoMotivo")
                        .HasColumnType("integer");

                    b.HasKey("cdProduto");

                    b.ToTable("cadProdutos");
                });

            modelBuilder.Entity("ControleDeEstoque.Domain.Entities.MovimentacaoEstoqueModel", b =>
                {
                    b.HasOne("ControleDeEstoque.Domain.Entities.MotivosModel", "Motivo")
                        .WithMany()
                        .HasForeignKey("cdMotivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleDeEstoque.Domain.Entities.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("cdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motivo");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
